// Generated by CoffeeScript 1.3.3
(function() {
  var CmdHooks, child_process, fs, sysPath;

  fs = require("fs");

  sysPath = require("path");

  child_process = require("child_process");

  module.exports = CmdHooks = (function() {

    CmdHooks.prototype.brunchPlugin = true;

    function CmdHooks(config) {
      this.config = config;
      null;
    }

    CmdHooks.prototype.onCompile = function(changedFiles) {
      var oncompile;
      oncompile = process.cwd() + "/hook_compile";
      if (fs.existsSync(oncompile)) {
        console.log("Execing", oncompile);
        return child_process.exec(oncompile, function(err, sout, serr) {
          if (err) {
            console.log("ERROR", err);
          }
          if (sout.length > 0) {
            return console.log("Out:" + sout);
          }
        });
      } else {
        return console.log("No hook", oncompile);
      }
    };

    return CmdHooks;

  })();

}).call(this);
